name: shield_android
description: Android implementation of the shield plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: shield
    platforms:
      android:
        package: com.sarisuki.shield.plugin
        pluginClass: ShieldPlugin
        dartPluginClass: ShieldAndroid

dependencies:
  flutter:
    sdk: flutter
  shield_platform_interface:
    path: ../shield_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
